from __future__ import annotations

import importlib.util
import json
import sys
import unittest
from datetime import timedelta
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
SPEC = importlib.util.spec_from_file_location("funding_mark", ROOT / "scripts/analyze_bnb_xrp_funding_mark_stress.py")
assert SPEC and SPEC.loader
MODULE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(MODULE)


class FundingMarkStressTest(unittest.TestCase):
    def test_approval_and_sealed_inputs_are_bound(self) -> None:
        approval = MODULE._approval(ROOT)
        self.assertTrue(approval["descriptive_analysis_authorized"])
        frames, integrity = MODULE.load_frames(ROOT)
        self.assertEqual(set(frames), {"BTC", "ETH", "BNB", "XRP"})
        self.assertEqual(len(integrity), 4)
        self.assertTrue(all(row["timestamp_alignment"] for row in integrity))

    def test_metric_counts_and_persistence_are_deterministic(self) -> None:
        dates = pd.date_range("2024-01-01", periods=6, freq="8h", tz="UTC")
        frame = pd.DataFrame({
            "date": dates,
            "funding_rate": [0.0, 2.0, 2.0, 0.0, 2.0, 0.0],
            "mark_return": [0.0, 3.0, 3.0, 0.0, 0.0, 0.0],
        })
        metrics = MODULE.window_metrics(frame, dates[0], dates[-1] + timedelta(hours=8), 1.0, 1.0)
        self.assertEqual(metrics["funding_stress_count"], 3)
        self.assertEqual(metrics["joint_stress_count"], 2)
        self.assertEqual(metrics["longest_joint_stress_run_8h_bars"], 2)

    def test_governed_artifact_has_zero_protected_access(self) -> None:
        path = ROOT / MODULE.ANALYSIS_PATH
        if not path.exists():
            self.skipTest("analysis artifact is generated by TASK-0191")
        result = json.loads(path.read_text(encoding="utf-8"))
        self.assertEqual(result["status"], "completed")
        self.assertEqual(result["governance"]["backtests"], 0)
        self.assertEqual(result["governance"]["validation_accesses"], 0)
        self.assertEqual(result["governance"]["holdout_accesses"], 0)
        self.assertFalse(result["governance"]["promotion_authorized"])


if __name__ == "__main__":
    unittest.main()
